spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-warship?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: a1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
